name: Metrics
on:
  schedule:
    - cron: 0 0 * * *
  push: {}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: header, activity, community, repositories
          config_order: base.header, isocalendar, languages, habits, reactions
          template: classic
          config_timezone: Europe/Paris

          # Isometric commit calendar
          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year

          # Most used languages
          plugin_languages: true
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_indepth: true

          # Coding habits
          plugin_habits: true
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: true
          plugin_habits_trim: true

          # Reactions
          plugin_reactions: true
          plugin_reactions_limit: 1000
          plugin_reactions_display: absolute
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
